export const faqData = [
  { id: 1, question: "Biz kimik?", answer: "Avtomobilinizi satmaq niyyətindəsinizsə və ya yenisini almaq fikrindəsinizsə, model avtomobilinizin qiymətini proqnozlaşdırmağa kömək edir. Sistem sizin üçün orta bazar qiymətini hesablayır və sonra hansı avtomobilin ehtiyaclarınıza daha uyğun olduğunu təmin edir. O, istənilən avtomobil satışı platformasına inteqrasiya oluna bilən vebsaytın bir hissəsi kimi yaradılacaq. Avtomobil sahibləri avtomobillərini satmaq üçün vebsayta daxil olduqda, qiymətlərə əhəmiyyətli dərəcədə təsir edən əsas avtomobil xüsusiyyətlərini daxil edə bilərlər. Daha sonra sistem müvafiq qiyməti qiymətləndirmək üçün orta statistik göstəricilərdən istifadə edəcək. Satıcı davam etməyi seçərsə, proqnozlaşdırılan dəyər dərhal vebsaytda elan olaraq göstəriləcək." },
  { id: 2, question: "Moto4 şərtləri nələrdir?", answer: "•Avtomobil mexaniki problemlərdən azaddır.  •Avtomobil maliyyə borclarından azaddır. " },
  { id: 3, question: "Daha sonra daha yaxşı qiymətə ala bilərəm?", answer: "Avtomobiliniz üçün təklif etdiyiniz qiymət həmin xüsusi marka və model üçün mövcud bazar vəziyyətindən asılıdır. Avtomobilinizi qiymətləndirdikdən sonra təqdim etdiyimiz yoxlama hesabatı yalnız 24 saat etibarlıdır." },
  { id: 4, question: "Maşınla bağlı problemim olsa kimə müraciət edim?", answer: "Avtomobilinizlə bağlı qeyri-təcili probleminiz varsa, ofisimizə zəng edin, biz sizə köməklik edəcəyik və bununla necə məşğul olmağı məsləhət görəcəyik." },
  { id: 5, question: "Avtomobilin qiymətinə hansı amillər təsir edir?", answer: "Avtomobilin vəziyyəti:Variant, yaş, istehsal statusu, sahiblik seriyası, qeydiyyat vəziyyəti, sığorta statusu və s." },
  { id: 6, question: "Məlumatlarınızı haradan əldə edirsiniz və nə dərəcə etibarlıdır?", answer: "Avtomobiliniz üçün təklif etdiyiniz qiymət həmin xüsusi marka və model üçün mövcud bazar vəziyyətindən asılıdır. Avtomobilinizi qiymətləndirdikdən sonra təqdim etdiyimiz yoxlama hesabatı yalnız 24 saat etibarlıdır." },
  
];
