import audi from "../assets/productImgs/audi.svg";
import bentley from "../assets/productImgs/bentley.svg";
import chevrolet from "../assets/productImgs/chevrolet.svg";
import ferrari from "../assets/productImgs/ferrari.svg";
import mercedesS500 from "../assets/productImgs/mercedesS500.svg";
import mercedesG55 from "../assets/productImgs/mercedesG55.svg";

export const products = [
  {
    id: 1,
    salon:false,
    name: "Audi A4",
    price: "21 000",
    currency: "$",
    capacity: "2.5L",
    year: "2018",
    distance: "180 800 km",
    location: "Sumqayıt",
    date: "Bugün 08:45",
    img: audi,
    leasing: false,
    credit: false,
    barter: true,
  },
  {
    id: 2,
    salon:false,
    name: "Bentley Mulsanne",
    price: "162 500",
    currency: "$",
    year: "2017",
    capacity: "6.5L",
    distance: "35 500 km",
    location: "Bakı",
    date: "Bugün 11:45",
    img: bentley,
    leasing: true,
    credit: true,
    barter: true,
  },
  {
    id: 3,
    salon:false,
    name: "Chevrolet Camaro",
    price: "23 500",
    currency: "$",
    year: "2020",
    capacity: "2.5L",
    distance: "95 500 km",
    location: "Bakı",
    date: "Bugün 11:45",
    img: chevrolet,
    leasing: true,
    credit: false,
    barter: true,
  },
  {
    id: 4,
    salon:false,
    name: "Mercedes-Benz G 55 AMG",
    price: "162 500",
    currency: "AZN",
    year: "2020",
    distance: "110 000 km",
    location: "Mingəçevir",
    date: "Bugün 19:45",
    capacity: "5.2L",
    img: mercedesG55,
    leasing: true,
    credit: false,
    barter: false,
  },
  {
    id: 5,
    salon:true,
    name: "Mercedes-Benz S 500",
    price: "75 500",
    currency: "$",
    year: "2021",
    distance: "110 000 km",
    location: "Bakı",
    capacity: "5.5L",
    date: "Bugün 11:45",
    img: mercedesS500,
    leasing: false,
    credit: false,
    barter: true,
  },
  {
    id: 6,
    salon:true,
    name: "Ferrari California",
    price: "185 000",
    currency: "$",
    capacity: "4.0 L",
    year: "2021",
    distance: "35 500 km",
    location: "Bakı",
    date: "Bugün 11:45",
    img: ferrari,
    leasing: true,
    credit: true,
    barter: false,
  },
];
